name: Module 01 - Microsoft Graph Authentication

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - DEV
          - UAT
          - PRD

jobs:

  authenticate:

    name: Authenticate to Microsoft Graph

    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Selected Environment
        run: |
          echo "========================================"
          echo "Environment : ${{ github.event.inputs.environment }}"
          echo "========================================"

      - name: Prepare Runner
        shell: pwsh
        run: |
          Install-Module Microsoft.Graph.Authentication `
            -Scope CurrentUser `
            -Force

      - name: Execute Authentication Module
        shell: pwsh
        env:
          CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: |
          ./Modules/Authentication/Connect-MicrosoftGraph.ps1