name: Module 03 - Get Group

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - DEV
          - UAT
          - PRD

      groupName:
        description: "Group Display Name"
        required: true
        type: string

jobs:
  get-group:

    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare Runner
        shell: pwsh
        run: |
          Import-Module Microsoft.Graph.Authentication
          Import-Module Microsoft.Graph.Groups

      - name: Execute Get Group Module
        shell: pwsh
        env:
          CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          GROUP_NAME: ${{ github.event.inputs.groupName }}


        run: |
         ./modules/groups/get-group.ps1 -GroupName $env:GROUP_NAME