name: Upload CSV

on:
  workflow_dispatch:
    inputs:

      file_name:
        description: "CSV file name (example: users.csv)"
        required: true
        type: string

      csv_content:
        description: "Paste CSV content"
        required: true
        type: string

permissions:
  contents: write

jobs:

  upload-csv:

    runs-on: ubuntu-latest

    steps:

      #------------------------------------------------------
      # Checkout csv-upload branch
      #------------------------------------------------------

      - name: Checkout csv-upload branch
        uses: actions/checkout@v4
        with:
          ref: csv-upload
          fetch-depth: 0

      #------------------------------------------------------
      # Validate File Name
      #------------------------------------------------------

      - name: Validate File Name
        shell: bash
        env:
          FILE_NAME: ${{ inputs.file_name }}
        run: |

          if [[ "$FILE_NAME" != *.csv ]]; then
            echo "Error: File must have .csv extension."
            exit 1
          fi

          if [[ "$FILE_NAME" == */* ]]; then
            echo "Error: File name must not contain directories."
            exit 1
          fi

          echo "File name validated: $FILE_NAME"

      #------------------------------------------------------
      # Create CSV File
      #------------------------------------------------------

      - name: Create CSV File
        shell: bash
        env:
            FILE_NAME: ${{ inputs.file_name }}
            CSV_CONTENT: ${{ inputs.csv_content }}
        run: |
            mkdir -p csv/pending
            printf '%s\n' "$CSV_CONTENT" > "csv/pending/$FILE_NAME"
      
      #------------------------------------------------------
      # Display CSV Header
      #------------------------------------------------------

      - name: Validate CSV
        shell: bash
        env:
          FILE_NAME: ${{ inputs.file_name }}
        run: |

          echo "CSV file:"
          cat "input/$FILE_NAME"

      #------------------------------------------------------
      # Commit CSV
      #------------------------------------------------------

      - name: Commit CSV to csv-upload
        shell: bash

        env:
            FILE_NAME: ${{ inputs.file_name }}
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git add "csv/pending/$FILE_NAME"

            if git diff --cached --quiet; then
            echo "No changes detected."
            exit 0
            fi

            git commit -m "data: upload $FILE_NAME to pending"

            git push origin csv-upload